### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by antonjb**
Merging Dev into master so we can deploy the meetup api work

### CODE REVIEW

**Comment by antonjb** [comment]
Well... darn. The build is working on my machine. Could be node versions, maybe?

**Comment by antonjb** [comment]
Yeah Netlify is using Node 6. Not sure how to change that just yet

**Comment by amykapernick** [comment]
Do we want the links to Meetup and Twitter and stuff opening in a new tab?

**Comment by antonjb** [comment]
@amykapernick we could do both of those. The .nvmrc is a good idea. That could be in another PR as this is dev -> master so those changes, if I understand the workflow should be feature branch -> dev.

**Pull request merged**
